name: medical_api
description: REST API service for medical system
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  postgres: ^2.6.1
  dotenv: ^4.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1